# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicRoom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MusicRoom

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
